#! /bin/sh

# Courtesy of Kristopher Bash, Senior Program Manager in Microsoft Open Technologies
# http://blogs.technet.com/b/privatecloud/archive/2014/05/19/powershell-dsc-for-linux-step-by-step.aspx

### BEGIN INIT INFO
# Provides:          omiserver
# Required-Start:    $local_fs $remote_fs
# Required-Stop:    $local_fs $remote_fs
# Default-Start:     3 4 5
# Default-Stop:      0 1 2 6
# Short-Description: omiserver initscript
# Description:      omiserver
### END INIT INFO

# Do NOT "set -e"

export OMI_HOME=/opt/omi-1.0.8/
DESC="omiserver"
NAME=omiserver
PIDFILE=/opt/omi-1.0.8/var/run/omiserver.pid
SCRIPTNAME=/etc/init.d/$NAME

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.0-6) to ensure that this file is present.
. /lib/lsb/init-functions

# Function that starts the daemon/service
do_start()
{
  /opt/omi-1.0.8/bin/omiserver -d
}

# Function that stops the daemon/service
do_stop()
{
  pid=`cat $PIDFILE`
  kill -9 $pid
}

case "$1" in
  start)
    do_start
    ;;

  stop)
    do_stop
    ;;

  restart|force-reload)
    do_stop
    do_start
    ;;

  *)
    echo "Usage: $SCRIPTNAME {start|stop|restart}" >&2
    exit 3
    ;;
esac
: